name: dbt-pr-init

on:
  workflow_call:
    secrets:
      ghPAT:
        required: true
    outputs:
      git_branch_sha:
        description: Github PR Hash
        value: ${{ jobs.generate-branch-sha.outputs.git_branch_sha }}

jobs:
  generate-branch-sha:
    runs-on: ubuntu-latest
    env:
      GITHUB_REF_NAME: ${{ github.head_ref }}
    outputs:
      git_branch_sha: ${{ steps.branch_sha.outputs.git_branch_sha }}
    steps:
      - name: Generate Branch SHA
        id: branch_sha
        run: |
          git_branch_sha=$(echo -n  "${{ env.GITHUB_REF_NAME }}" | sha256sum | tr -d "[:space:]-" | cut -c -8)
          echo "git_branch_sha=$git_branch_sha" >> "$GITHUB_OUTPUT"

  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.ghPAT }}"

  pr-semantic:
    needs: generate-branch-sha
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.ghPAT }}
        with:
          types: |
            fix
            feat
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
